/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocalePracticeAreasIndexRouteImport } from './routes/$locale/practice-areas/index'
import { Route as LocalePracticeAreasSlugRouteImport } from './routes/$locale/practice-areas/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePracticeAreasIndexRoute =
  LocalePracticeAreasIndexRouteImport.update({
    id: '/practice-areas/',
    path: '/practice-areas/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocalePracticeAreasSlugRoute = LocalePracticeAreasSlugRouteImport.update({
  id: '/practice-areas/$slug',
  path: '/practice-areas/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/practice-areas/$slug': typeof LocalePracticeAreasSlugRoute
  '/$locale/practice-areas/': typeof LocalePracticeAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/practice-areas/$slug': typeof LocalePracticeAreasSlugRoute
  '/$locale/practice-areas': typeof LocalePracticeAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/practice-areas/$slug': typeof LocalePracticeAreasSlugRoute
  '/$locale/practice-areas/': typeof LocalePracticeAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/'
    | '/$locale/practice-areas/$slug'
    | '/$locale/practice-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/about'
    | '/$locale'
    | '/$locale/practice-areas/$slug'
    | '/$locale/practice-areas'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/about'
    | '/$locale/'
    | '/$locale/practice-areas/$slug'
    | '/$locale/practice-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/practice-areas/': {
      id: '/$locale/practice-areas/'
      path: '/practice-areas'
      fullPath: '/$locale/practice-areas/'
      preLoaderRoute: typeof LocalePracticeAreasIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/practice-areas/$slug': {
      id: '/$locale/practice-areas/$slug'
      path: '/practice-areas/$slug'
      fullPath: '/$locale/practice-areas/$slug'
      preLoaderRoute: typeof LocalePracticeAreasSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePracticeAreasSlugRoute: typeof LocalePracticeAreasSlugRoute
  LocalePracticeAreasIndexRoute: typeof LocalePracticeAreasIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePracticeAreasSlugRoute: LocalePracticeAreasSlugRoute,
  LocalePracticeAreasIndexRoute: LocalePracticeAreasIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
